name: Testing

on: 
  pull_request:
  push:
    branches: [ main ]
    paths: 
        - 'utils/**'
        - '.github/**'
        - 'Dockerfile*'
        - '*.{yaml, yml}'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: chmod +x entrypoint.sh
      - name: head-is-greater-than-base
        uses: ./
        with:
          head: '2.0.0'
          base: '1.0.0'
          operator: '>'
      - name: head-is-less-than-base
        uses: ./
        with:
          head: '1.0.0'
          base: '2.0.0'
          operator: '<'
      - name: head-is-the-same-as-base
        uses: ./
        with:
          head: '1.0.0'
          base: '1.0.0'
          operator: '='
      - name: head-is-the-same-as-base
        uses: ./
        with:
          head: '1.0.0'
          base: '1.0.0'
          operator: '='
      - name: head-is-equal-to-or-greater-than-base
        uses: ./
        with:
          head: '1.0.0'
          base: '1.0.0'
          operator: '>='
      - name: head-is-equal-to-or-less-than-base
        uses: ./
        with:
          head: '1.0.0'
          base: '1.0.0'
          operator: '<='
      - name: build-numbers-are-ignored
        uses: ./
        with:
          head: '1.0.0+1'
          base: '1.0.0+25'
          operator: '='