name: Version Control

on: 
  push:
    branches:
      - main

jobs:
  bump_version:
    runs-on: ubuntu-latest
    name: Bump Version
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Github Tag Bump
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false